name: yolo11xseg-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23.5,<1.25.0  # Example of tighter version constraint
  - matplotlib>=3.7.1,<3.8.0
  - opencv-contrib-python>=4.7.0,<4.8.0 # Or opencv
  - pillow>=9.5.0,<9.6.0
  - pyyaml>=6.0,<6.1.0
  - scipy>=1.10.1,<1.11.0
  - tqdm>=4.65.0,<4.66.0
  - pandas>=2.0.0,<2.1.0
  - seaborn>=0.12.2,<0.13.0
  - ipython>=8.12.0,<8.13.0
  - psutil>=5.9.5,<5.10.0
  - tensorboard>=2.13.0,<2.14.0
  - shapely>=2.0.0

  # PyTorch with CUDA
  - pytorch>=2.1.0,<2.2.0
  - torchvision>=0.16.0,<0.17.0
  - pytorch-cuda=12.1
  - cudatoolkit>=12.1,<12.2 # Pin CUDA toolkit

  # Performance optimizations
  - cudnn>=8.9.2,<8.10.0
  - ninja>=1.11.1,<1.12.0
  - packaging>=23.1,<23.2
  - protobuf>=4.23.0,<4.24.0

  # Additional optimization packages
  - pip:
    - ultralytics>=8.1.21,<8.2.0  # Latest Ultralytics
    - onnx>=1.14.0,<1.15.0
    - onnxruntime-gpu>=1.15.1,<1.16.0
    - thop>=0.1.1,<0.2.0  # For FLOPs calculation
    - pycocotools>=2.0.6,<2.1.0
    - albumentations>=1.3.1,<1.4.0
    - segment-anything>=1.0,<1.1.0
    - rich>=13.5.0,<13.6.0  # Better console output
    - wandb>=0.15.0,<0.16.0  # Weights & Biases logging
    - pytorch-lightning>=2.1.0,<2.2.0  # Lightning for better training structure
    - timm>=0.9.5,<0.10.0  # PyTorch Image Models
    - nvidia-ml-py>=11.525.131,<11.526.0  # NVIDIA Management Library
    - imgaug>=0.4.0,<0.5.0  # Image augmentation library
    - setuptools>=68.0.0,<69.0.0
    - wheel>=0.40.0,<0.41.0

variables:
  PYTORCH_CUDA_ALLOC_CONF: 'max_split_size_mb:128'
  CUDA_MODULE_LOADING: 'LAZY'
